In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.2.3'

In [4]:
df = pd.read_csv('laptops.csv')

In [5]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [42]:
df['Brand'].nunique()

27

In [23]:
len(brands)

27

In [49]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             0
Touch              0
Final Price        0
dtype: int64

In [26]:
df.groupby('Brand').max('Final Price')

RAM  Storage  Screen  Final Price
Brand                                              
Acer               32     1000    17.3      3691.00
Alurin             16      512    15.6       869.00
Apple              32     2000    16.2      3849.00
Asus               64     4000    18.0      5758.14
Deep Gaming        64     2000    17.3      1639.01
Dell               32     1000    17.0      3936.00
Denver              4      256    14.0       329.95
Dynabook Toshiba   16      512    15.6      1805.01
Gigabyte           32     2000    17.3      3799.00
HP                 32     1000    17.3      5368.77
Innjoo              8      512    15.6       431.38
Jetwing             8      256    15.6       469.27
LG                 32     2000    17.0      2399.00
Lenovo             32     2000    17.3      5018.14
MSI               128     2000    17.3      7150.47
Medion             32     2000    17.3      3799.00
Microsoft          32     2000    15.0      3747.91
Millenium          16      500    15.6      2312.71
PcCom              32     1000    17.3      1949.90
Primux              8      512    15.6       599.41
Prixton             4      128    15.6       329.95
Razer              32     2000    17.3      4999.01
Realme              8      512    14.0       999.00
Samsung            32     1000    16.0      3699.01
Thomson             8      512    15.6       436.56
Toshiba             8      256    14.0       799.00
Vant               40     1000    14.0      1217.01

In [32]:
screen_median = df['Screen'].median()
screen_median

np.float64(15.6)

In [47]:
screen_mode = df['Screen'].mode()
screen_mode[0]

np.float64(15.6)

In [48]:
df['Screen'] = df['Screen'].fillna(screen_mode[0])

In [50]:
df['Screen'].isnull().sum()

np.int64(0)

In [52]:
screen_median = df['Screen'].median()
screen_median

np.float64(15.6)

In [61]:
df_innjoo = df[df['Brand'] == 'Innjoo']

In [62]:
df_innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [65]:
df_innjoo = df_innjoo[['RAM','Storage','Screen']]

In [66]:
df_innjoo

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [67]:
X = np.array(df_innjoo)

In [68]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [75]:
X_transpose = X.T

In [76]:
X_transpose

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [77]:
XTX = X.dot(X_transpose)

In [78]:
XTX

array([[ 65843.36, 131379.36,  16635.96,  16651.96,  33035.96,  33035.96],
       [131379.36, 262451.36,  33019.96,  33035.96,  65803.96,  65803.96],
       [ 16635.96,  33019.96,   4310.81,   4318.81,   8414.81,   8414.81],
       [ 16651.96,  33035.96,   4318.81,   4330.81,   8426.81,   8426.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81]])

In [81]:
XTX_inverse = np.linalg.pinv(XTX)

In [82]:
XTX_inverse

array([[ 0.07685672, -0.03540126, -0.12193106,  0.04199099,  0.0139265 ,
         0.0139265 ],
       [-0.03540126,  0.01651252,  0.05568098, -0.01960876, -0.00663032,
        -0.00663032],
       [-0.12193106,  0.05568098,  0.19459549, -0.0659823 , -0.02157929,
        -0.02157929],
       [ 0.04199099, -0.01960876, -0.0659823 ,  0.02329208,  0.00789214,
         0.00789214],
       [ 0.0139265 , -0.00663032, -0.02157929,  0.00789214,  0.00275294,
         0.00275294],
       [ 0.0139265 , -0.00663032, -0.02157929,  0.00789214,  0.00275294,
         0.00275294]])

In [74]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [84]:
result = XTX_inverse * X_transpose

ValueError: operands could not be broadcast together with shapes (6,6) (3,6) 